version: "3"
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    build:
      context: /root/complex/nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
    restart: always
  server-api:
    depends_on:
      - postgres
    build:
     context: /root/complex/server
     dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - /root/complex/server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGUSET=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      context: /root/complex/client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - /root/complex/client:/app
  worker:
    build:
      context: /root/complex/worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - /root/complex/worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
